# Generated by Django 6.0.1 on 2026-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(
             default='TEMP', 
             max_length=10, 
             help_text='es: DEV, DSGN, PHOTOGRAPH, WEB, etc.'
             ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='matricola',
            field=models.CharField(
             blank=True, 
             max_length=20, 
             unique=True
             ),
        ),
        # Rimuovi eventuali campi obsoleti (es. classroom)
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),

        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'course')},
        ),
    ]