# Generated by Django 4.2.27 on 2026-01-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('core', '0002_alter_absence_options_alter_absence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='students.student'),
        ),
    ]
