# Generated by Django 6.0.1 on 2026-01-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_absence_options_alter_absence_student'),
        ('students', '0002_remove_student_classroom_student_course_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='comment',
        ),
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='students.student'),
        ),
    ]
